### ISSUE TITLE
New functions `try-darken` and `try-lighten`

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-theme-default#197]
We need functions to perform lighten and darken, but if they reach a certain threshold to revert to the other function

```scss
darken(#111, 10) // => #000
try-darken(#111, 10) // => #2b2b2b
```
@gyoshev @inikolova @mvgmvg @theOrlin any thoughts?

**Comment by gyoshev** [comment]
What is the use case that requires these?

**Comment by joneff** [comment]
If you want to make a usually light theme dark, you will hit this limitation. Currently, it applies to default-v2 and bootstrap themes.

(And all ajax themes)

**Comment by joneff** [comment]
A quick prototype:

```scss
@function try-darken( $color, $amount, $threshold: black ) {
  $amount: if(unitless($amount), $amount, ($amount / 1%));

  $result: darken( $color, $amount );
  $alt-result: darken( $color, ($amount - 1) );
  
  @if ($result == $threshold) and ($alt-result == $threshold) {
    @return lighten( $color, $amount );
  }
  @return $result;
}

@function try-lighten( $color, $amount, $threshold: white ) {
  $amount: if(unitless($amount), $amount, ($amount / 1%));

  $result: lighten( $color, $amount );
  $alt-result: lighten( $color, ($amount - 1) );
  
  @if ($result == $threshold) and ($alt-result == $threshold) {
    @return darken( $color, $amount );
  }
  @return $result;
}
```

Note that comparing colors could be later improved with `is-darker` and `is-lighter` functions. For this initial version, direct comparison for black / white will suffice.

```scss
try-darken( #040404, 10); // => threshold, #1e1e1e
try-darken( #fafafa, 10); // => ok, #e1e1e1
try-darken( red, 10); // => ok, #cc0000
try-lighten( #040404, 10); // => ok, #1e1e1e
try-lighten( #fafafa, 10); // threshold, #e1e1e1
try-lighten( red, 10); // threshold, #cc0000
```
