### ISSUE TITLE
Multiselect: Increase close button hit area

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-theme-default#620]
Follow up from #576, the close button should be easier to click. This can be achieved by wrapping it in a container with the size of the buttons.

**Comment by joneff** [comment]
```scss
.k-multiselect-wrap .k-button .k-select {
    align-self: stretch;
}
```
