### ISSUE TITLE
Pivotgrid stretched beyond container in IE

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-theme-default#647]
### Description
The Pivotgrid in IE with the new SASS themes is stretched horizontally beyond its container.

See http://demos.telerik.com/kendo-ui/pivotgrid/index in IE with a SASS theme.

### Screenshot
https://www.screencast.com/t/dSaxDjkmUqp

TID: 1139777

**Comment by MilenaCh** [comment]
Export functionality should be verified after the fix.
Currently, exported pdf document in IE looks like:
https://www.screencast.com/t/Imd4BHx8

**Comment by joneff** [comment]
Needs https://github.com/telerik/kendo-themes/pull/214

The workaround is to set fixed width to the first cell and fixed layout to the table only for IE 11. The width can be customized via this rule:

```css
.k-ie11 .k-pivot-layout > tbody > tr > td:first-child {
    width: 280px; /* change this value */
}
```
