### ISSUE TITLE
Sorting icon is not visible when header text is long but the column width is small

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-theme-default#708]
Sorting icon is not visible when header text is long but the column width is small. Can be observed in the Master-Detail Grids demo -> http://www.telerik.com/kendo-angular-ui/components/grid/hierarchy/

To reproduce the issue sort the CategoryID column

**Comment by gyoshev** [comment]
Addressing this issue requires either a change in the grid rendering (to use flexbox and target the text-overflow only on the column title), or the design of the sortable indicator. @joneff @lkarakoleva what do you think?

**Comment by gyoshev** [comment]
A workaround for this issue is to move the sort indicator icon before the header text, for example with the following rule:

```css
.k-grid-header .k-header .k-link .k-icon {
    position: absolute;
    left: -8px;
    top: 8px;
}
```

![image](https://user-images.githubusercontent.com/90405/38137642-83d2f350-342e-11e8-9f7e-311da3975972.png)
