### ISSUE TITLE
Inconsistent header font size in DateInputs

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#799]
Calendar's `th` font size:

```css
.k-calendar th {
...
    font-size: 12px;
...
}
```

Should be the same as the `th` in the TimePicker (10px):
```css
.k-calendar th {
...
    font-size: 10px;
...
}
```

#### Reference PSD: 
https://github.com/telerik/kendo-ux/blob/master/themes/default/datetimepickers.psd
