### ISSUE TITLE
Toolbar elements layout inconsistencies

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-default#805]
The following issues with toolbar elements are observed:
- [ ] The dropdowns labels are not vertically aligned - http://demos.telerik.com/kendo-ui/toolbar/integration
- [x] ~~There is no space between the widgets and the ToolBar top and bottom borders~~
![image](https://user-images.githubusercontent.com/7202037/33423221-e1494e3e-d5c0-11e7-9df6-199e969211e0.png)

The second issue is not reproducible with R2 2018 SP1 - 2018.1.221
![image](https://user-images.githubusercontent.com/6614183/39181509-958b1fa8-47c2-11e8-9b83-2b9c0f401c77.png)

**Comment by joneff** [comment]
This is a two part issue. Here is the initial fix:

```scss
.k-toolbar>div:not(.overflow-anchor):not(.k-separator):not(.k-button-group) {
    align-items: center;
}
```

Then, we must add `k-template` to template containers, so we can target this.
