### ISSUE TITLE
Icon modifiers

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-theme-default#806]
With just a few styles, we can compound icons:

```html
<span class="k-icon k-i-plus k-icon-with-modifier">
    <span class="k-icon k-icon-modifier k-i-unlock"></span>
</span>
```

```css
.k-icon-with-modifier {
  position: relative;
  margin: 0.25em;
}
.k-icon-modifier {
  position: absolute;
  font-size: .5em;
  bottom: 0;
  right: 0;
  margin: 0 -.5em -.5em 0;
}
```

[Dojo snippet](http://dojo.telerik.com/uMeFak/2)
