### ISSUE TITLE
Grid filter menu icon distorts column header rendering in IE

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#834]
Observable in the online demos:

[https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#toc-filter-menu](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#toc-filter-menu)

![image](https://user-images.githubusercontent.com/7533599/34249957-1986624e-e644-11e7-9c05-fbf94a38d003.png)

Suggested CSS workaround:

```
styles: [ `
      >>> .k-grid .k-grid-filter { position: absolute; top: 8px; right: 4px; }
      >>> .k-grid .k-grid-header .k-link { padding-right: 32px; }
    `],
```
[https://plnkr.co/edit/S0OxoRaZQ59cYMipxx8V?p=preview](https://plnkr.co/edit/S0OxoRaZQ59cYMipxx8V?p=preview)

**Comment by gyoshev** [comment]
The fix requires the rendering of the `k-filterable` class on the grid. Until it is added, the following workaround works without obstructing other scenarios:

```css
      .k-grid .k-header kendo-grid-filter-menu + .k-link {
        margin-right: calc(10px + 1.4285714286em);
      }
```
